### ISSUE TITLE
Thanking multiple people

### ISSUE THREAD

**Issue by hexus** [Claromentis/cla-thankyou#1]
Kerensa mentioned on Innovate that a good enhancement would be thanking multiple people at once.

**Comment by astax-t** [comment]
https://github.com/Claromentis/app-thankyou/commit/979d1f04933cec23b8e50139b64c32d835292ae4

**Comment by hexus** [comment]
:ok_hand:

Feel free to close or just post here when you're completely happy with the implementation. If you are already then we can close this. :)

**Comment by astax-t** [comment]
Done in version 1.1.0
