### ISSUE TITLE
Disable component title  - say thank you is displaying as a link

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#10]
Hello,

not sure if the "Say thank you" button should be changed to a link if I disable component title? 

![thankyou](https://user-images.githubusercontent.com/8656805/36681733-5d474474-1b11-11e8-90b5-7538b1fa532a.jpg)

**Comment by astax-t** [comment]
Yes, it should be shown as a link rather than button if the component title is hidden.
