### ISSUE TITLE
Edit/delete thank you note - page jumps to the top

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#11]
Hello,

When I edit/delete "thank you" note, the page jumps to the top.

**Comment by jjbunce** [comment]
Hi Olia, 
The page will no longer jump t the top when the edit/delete buttons are clicked.

Thanks

**Comment by olganovosad** [comment]
tested ie, safari, firefox, chrome in win and linux servers  on 8.3 and 8.2 versions
