### ISSUE TITLE
User's profile - thank you: design fix is required

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#13]
Hello,

In user's profile, in thank you tab some design fixes are required:

Tested in chrome

![claromentis - olia 1 - viewing profile 2018-02-27 12-18-16](https://user-images.githubusercontent.com/8656805/36728480-ca863c00-1bb8-11e8-94fc-e708aa33eb31.jpg)

**Comment by jjbunce** [comment]
Hi Olia, 
Margin has been added to the bottom of the button now

Thanks

**Comment by olganovosad** [comment]
this is fixed, tested ie, firefox, chrome, safari
