### ISSUE TITLE
Add a gap between user profile images

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#16]
Hello,

I've thanked several users. There is a gap required between users profile images if they are displaying on the next line.

![claromentis - olia s site 2018-02-28 09-29-31](https://user-images.githubusercontent.com/8656805/36780151-088f5ac0-1c6a-11e8-82e9-1392bd07adff.jpg)

**Comment by jjbunce** [comment]
Hi Olia, 
I have corrected issues here, I've made the profile pictures slightly smaller and added margin below each image.

Thanks

**Comment by olganovosad** [comment]
thank you, tested ie, safari, firefox, chrome
