### ISSUE TITLE
User to show thanks for one user only - should I still be able to thank other users?

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#17]
Hello,

Let me know if this is correct as I'm not sure.

I have selected "User to show thanks for one user only" In my understanding it should show thanks for this user only.

However, should I be able to thanks any other user in this case as currently, it allows to thank this selected user only.

![claromentis - olia s site 2018-02-28 09-40-29](https://user-images.githubusercontent.com/8656805/36780802-ed40b474-1c6b-11e8-83e7-2fee6f9d0251.jpg)

**Comment by astax-t** [comment]
I think it's fine to have just one user. This component is rarely used for a specific user and when it is, this is normally on user's profile page. People can thank multiple users via generic component.

What I noticed though is that the name is not aligned with the label. This needs to be fixed.

**Comment by olganovosad** [comment]
ok, thank you for clarifying.

yep that issue will be reported separately.
