### ISSUE TITLE
When component is displaying thank you for specific user, the username is not aligned when hitting Say thank you button

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#18]
Hello,

I have selected to show thank you for specific user. When I hit Say thank you button, the user name is not aligned with the field label:

![claromentis administrator - viewing profile - win82 system 2018-02-28 09-56-26](https://user-images.githubusercontent.com/8656805/36781391-a931c49c-1c6d-11e8-9a86-be0eb736f4b9.jpg)

**Comment by jjbunce** [comment]
Hi Olia,
I've corrected the alignment on the user profile page now.

Thanks

**Comment by olganovosad** [comment]
tested ie, safari, chrome, firefox
