### ISSUE TITLE
Highlight error messages when required fields are missing

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#20]
Hello,

Shall we somehow highlight error messages when required fields are missed in pop up? or may be event change error message design slightly?

Please see the current design:

![claromentis - olia s site 2018-03-01 11-55-34](https://user-images.githubusercontent.com/8656805/36843852-2868884c-1d48-11e8-82b0-c73d066a59a5.jpg)

**Comment by jjbunce** [comment]
HI Olia, 
I've moved the 'This field is required' text to directly below the user picker now.

Thanks

**Comment by olganovosad** [comment]
tested ie, firefox, safari, chrome in 8.2 and 8.3
