### ISSUE TITLE
Improve "Show profile image" option in the component

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#21]
Hello,

This was raised in product team.

Shall we amend the look of "Show profile image" option in the component. As per screenshot below you can see that it's no looking nice, especially if there are several users selected.

![claromentis - olia s site 2018-03-01 12-08-25](https://user-images.githubusercontent.com/8656805/36844228-c701f6fe-1d49-11e8-8e16-aeabaa51f2e1.jpg)

**Comment by jjbunce** [comment]
Hi Olia,
I don't think we have much choice but to have the images wrap to the next line but I have made it I little more obvious that they're separate from the text and made the profile images slightly smaller and improved spacing.

Thanks

**Comment by olganovosad** [comment]
ok, I've tested that in ie, chrome, firefox, safari
