### ISSUE TITLE
Add 20 thank yous - not all are displaying in user's profile, paginations is required in thank you admin as the list is too long

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#23]
Hello,

Shall we add pagination or Show more link if there are lots of thanks yous in user's profile and admin panel?

Currently, in user's profile I cannot see all the thank you's and I've added 20 of them for a user.

In thank you admin panel the list is displaying too long

![claromentis - olia 1 - viewing profile 2018-03-01 15-58-06](https://user-images.githubusercontent.com/8656805/36854746-9f51ba98-1d69-11e8-8677-29dee9ae0c01.jpg)

**Comment by michaelchristian** [comment]
@hexus  Should we just display all thank you in user profile to be consistent with no pagination yet on this version rather than stop after 20

**Comment by astax-t** [comment]
There must be a limit, otherwise the list may grow too big. And really there is no need to view too far back. Treat this the same way as "what's new" where we display the most recent updates and not use any pagination.

Since we have admin area, it's still possible to retrieve historic data if needed,

**Comment by hexus** [comment]
Yeah, I was only happy leaving no limit in the admin panel. I also wanted to implement "show more" style pagination for the admin panel, in case this list gets really big for some systems.

Until we implement pagination, this should be left as it is. See #7. I'm closing this as it's essentially a duplicate.
