### ISSUE TITLE
Date "Thank you" posted

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#24]
Hello,

it's probably designed this way...however, it's better to confirm.

We can now see when the Thank you was posted. For example, today is 2nd of March. Thank you is posted on 19th of January. It says it was posted 1 month ago, which is not really true..it's probably updates when it reaches 2 months date..but is there something to improve it or shall we leave it as it is now?

![home page - codedev claromentis 2018-03-02 09-58-37](https://user-images.githubusercontent.com/8656805/36893905-a6bc21d6-1e01-11e8-89c2-417e31486c6e.jpg)

**Comment by astax-t** [comment]
It's fine now. We don't need to show "1.5 months ago".
