### ISSUE TITLE
Different font is used for different browser window size

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#25]
Hello,

We've got different font for Thank you posts when using different browser window size.

![claromentis - olia smolnikova o graddy - viewing profile 2018-03-02 14-06-30](https://user-images.githubusercontent.com/8656805/36902620-07e2ed84-1e23-11e8-90b5-a41a9bd619d3.jpg)
![claromentis - olia smolnikova o graddy - viewing profile 2018-03-02 14-06-20](https://user-images.githubusercontent.com/8656805/36902621-07f9cfae-1e23-11e8-95b2-2080dfb10616.jpg)

**Comment by jjbunce** [comment]
Hi Olia, 
The issue with the text changing style at different screen sizes has been fixed now. 

Thanks

**Comment by olganovosad** [comment]
test ie, safari, chrome, firefox
