### ISSUE TITLE
Blocked users are still visible in the component

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#3]
Hello,
Should blocked user still be visible in the component?

Currently it is visible, but when you click username it doesn't redirect to profile, which is correct.

![blocked user](https://cloud.githubusercontent.com/assets/8656805/21770874/1aa619d0-d67d-11e6-8e97-9643671ceae1.png)

**Comment by astax-t** [comment]
I think blocked users still should be displayed - if someone earlier said thanks to a colleague who's left the company, why should that "thank you" vanish?
