### ISSUE TITLE
CB_notifs - set thank you communication to email only: user still received in-system when somebody says thank you to him/her

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#30]
Hello,

I have set the thank you communication settings to Email only and no in-system notification.

When somebody says thank you the user still sees in-system notification:

![Olia's - Notifications settings 2019-03-27 12-12-53](https://user-images.githubusercontent.com/8656805/55075030-cd807400-5089-11e9-804d-6d6025d91422.jpg)

**Comment by hexus** [comment]
#27

**Comment by olganovosad** [comment]
I tested blog with the same settings and blog does send email only and no in-system notification, so I guess this is thank you issue. Or we have a different way of communication settings working which I'm not aware of.

**Comment by olganovosad** [comment]
fixed
