### ISSUE TITLE
CB_notifs - set than kyou notifications for daily digest: email still goes through

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#31]
Hello,

I have set up thank you notifications for Daily Digest, but I still receive email when somebody says thank you to me:

![MailHog 2019-03-27 12-27-27](https://user-images.githubusercontent.com/8656805/55075802-c9555600-508b-11e9-80f0-d2220a1f0de3.jpg)
![Olia's - Notifications settings 2019-03-27 12-27-09](https://user-images.githubusercontent.com/8656805/55075803-c9555600-508b-11e9-9435-8aae45072106.jpg)

**Comment by hexus** [comment]
#27

**Comment by hexus** [comment]
Hey @olganovosad, can you confirm that this only happens for notifications from the Thank You component, and not other modules too?

**Comment by olganovosad** [comment]
Hi Chris,

sure I can check that for other modules, but the thing is that Line manager notifications are working as expected in this case, but not for user who's being thanked.

**Comment by andy-ce-taylor** [comment]
In [Communication Panel][Reset notifications], for user X, I set it so that all Holiday messages should be sent to "E-mail only (No in-system notification at all)".

When logged in as X, I requested a holiday and received the normal in-system notification.

**Comment by hexus** [comment]
Just realised, this will be related to #32. The type of the notification. 🙂 

Please retest this alongside #32 now that Andy has addressed that issue.

**Comment by olganovosad** [comment]
it's now doesn't send an email and works as expected
