### ISSUE TITLE
Labels for both in-system notification, for a user and line manager, should be the same

### ISSUE THREAD

**Issue by olganovosad** [Claromentis/cla-thankyou#32]
Hello,

Discussed with Gili.

The label for in-system notifications should be "Thank you" for both notifications for a user and for line manager.

Currently, for user it says "People":

![Olia's - Home Page 2019-03-27 12-41-33](https://user-images.githubusercontent.com/8656805/55077429-9ca33d80-508f-11e9-9483-ed94a683a073.jpg)

**Comment by hexus** [comment]
#27

**Comment by andy-ce-taylor** [comment]
v3.2 (origin) uses IMessage::TYPE_PEOPLE at the moment - and there isn't an iMessage for "Thank You".
The CB_notifs branch has a new "IM_TYPE_THANKYOU" which can set that label to "Thank You".
I'll correct it on the branch then it can be merged in along with the rest of it when the time comes.

**Comment by olganovosad** [comment]
the label is fixed . tested 8.3 and 8.7
