### ISSUE TITLE
Admin panel - Thanks component pagination

### ISSUE THREAD

**Issue by hexus** [Claromentis/cla-thankyou#7]
Currently the Thank You Messages admin panel will list all thank you messages in the system.

"Show more" style pagination should be implemented to ensure that this performs well.

The pagination would also be useful for front-end display, in case users want to see further back.

**Comment by olganovosad** [comment]
Hello,

The pagination  is implemented in admin panel, however in use profile as far as I understood it won't be implemented.

What I've noticed that in Thank you Tab there is total number of thank yous, however it's defaulted to 10 which will mislead users.

Comments from product channel:

Mike C: i think it make sense to have pagination in user profile as well ? or at least limit to large number? I agree it is confusing when user sees 22 but only see 10 without other messages

Gili: Yes I agree, I think if we're showing '22' as the number of thank you's this is what the user should see
Even if they have 100 it's up to them if they want to scroll endlessly, even with no pagination 🙂



![claromentis - olia 1 - viewing profile 2018-03-06 12-17-55](https://user-images.githubusercontent.com/8656805/37032218-937046a8-2139-11e8-8a0f-1a3cce77e644.jpg)

**Comment by astax-t** [comment]
Being able to see older thanks on user profile is a different task, which needs to be solved differently (if needs at all) - perhaps have "load more" at the bottom of the list.

Since the original problem has been resolved, I'm closing this issue.
